version: '3'
services:
  backend:
    build:
      context: ./server
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      PORT: 4000
    volumes:
      - ./server:/app  # Bind mount local 'server' directory to '/app' in container
      - /app/node_modules
    command: npm run dev  # Assuming `npm run dev` starts a development server with hot-reloading

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./client:/app  # Bind mount local 'client' directory to '/app' in container
      - /app/node_modules
    command: npm start  # Assuming `npm start` starts a development server with hot-reloading
