version: '3'
services:
  backend:
    build:
      context: ./server
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      PORT: 4000
    command: npm start

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "3000:80"
    environment:
      NODE_ENV: production
    command: nginx -g "daemon off;"
